/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package commission;

import commission.service.Commission;

public class Library {
    public boolean someLibraryMethod() {
        Commission commission = new Commission.Builder()
                .build();
        System.out.println(commission.getSize());
        return true;
    }
}
